### ISSUE TITLE
Migrate layout folder to TypeScript and Next.js

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/anabada-refactoring#16]
## Description
**A clear and concise description of what the problem is.**

## To-do
**A clear and concise description of what you have to do.**
- [ ] Migrate JavaScript file to TypeScript
- [ ] Refactor code to remove unnecessary logic, extract reusable logic, and create components as needed.
- [ ] Separate styles into their own files

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
