### ISSUE TITLE
Migration of notification components to TypeScript with Next.js

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/anabada-refactoring#18]
## Description
**A clear and concise description of what the problem is.**
The goal of this issue is to migrate notification components to TypeScript with Next.js. This will involve converting existing JavaScript code to TypeScript, which will help catch type errors and improve the maintainability of the codebase. Additionally, I will separate the React-Query hook for separate concerns and to reduce complicated code.

## To-do
**A clear and concise description of what you have to do.**
- [ ] Convert existing JavaScript code to TypeScript
- [ ] Separate React-Query hook for separate concerns
- [ ] Refactor code to reduce complexity

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
