### ISSUE TITLE
Migrate posts page to Next.js with Typescript

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/anabada-refactoring#2]
## Description
**A clear and concise description of what the problem is.**
Migrate posts page to Next.js with Typescript

## To-do
**A clear and concise description of what you have to do.**
- [x] Convert usePosts react-query custom hook to typeScript
- [x] Convert posts page to typeScript
- [x] Implement pre-rendering with getStaticProps in Next.js
- [x] Make reusable components to avoid duplicate code

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
