### ISSUE TITLE
Migrate Mypage page components with Typescript and Next.js

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/anabada-refactoring#24]
## Description
**A clear and concise description of what the problem is.**

## To-do
**A clear and concise description of what you have to do.**
- [ ] Add type to catch errors at compile-time, ensuring safer and more reliable code.
- [ ] Separate react-query hooks for separate concerns
- [ ] Make reusable components for maintainability and scalability

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
