### ISSUE TITLE
Migration of chat page components to TypeScript with Next.js 

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/anabada-refactoring#25]
## Description
**A clear and concise description of what the problem is.**
The goal of this issue is to migrate chat pages to TypeScript with Next.js. This will involve converting existing JavaScript code to TypeScript, which will help catch type errors and improve the maintainability of the codebase. Additionally, I will separate the React-Query hook for separate concerns and to reduce complicated code.

## To-do
**A clear and concise description of what you have to do.**
- [ ]Add type to catch errors at compile-time, ensuring safer and more reliable code.
- [ ] Separate react-query hooks for separate concerns
- [ ] Make reusable components for maintainability and scalability

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
