### ISSUE TITLE
Migrate meetadd page to typescript with Next.js

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/anabada-refactoring#30]
## Description
**A clear and concise description of what the problem is.**

## To-do
**A clear and concise description of what you have to do.**
- [ ] Update all relevant files in the meet add a feature to use TypeScript, including the main meet add a page, any related components, and any supporting files such as stylesheets or utility functions.
- [ ] Separate custom hooks for separation of concerns
- [ ] Add type annotations to JavaScript code can help make it more robust, easier to understand and maintain, and potentially faster.

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
