### ISSUE TITLE
Migrate post detail page to Next.js with Typescript

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/anabada-refactoring#9]
## Description
**A clear and concise description of what the problem is.**

## To-do
**A clear and concise description of what you have to do.**
- [x] Add the required type
- [x] Separate react query hooks
- [x] Separate common components to make reusable

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
